In [13]:
from dataset_summarizer import DatasetSummarizer
from hf_loader import HFDatasetLoader

In [14]:
# Puedes elegir cualquiera de las 11 tablas (ej: 'match_stats', 'players', 'teams', 'leagues', etc.)
TABLA_ELEGIDA = "match_stats"

loader = HFDatasetLoader(
    dataset_name="eatpizzanot/soccer-dataset",
    name=TABLA_ELEGIDA,
    split="train",
)
df_original = loader.load_data()

print(f"--- DataFrame Cargado Original ('{TABLA_ELEGIDA}') ---")
print(f"Filas totales: {len(df_original)}")
display(df_original.head())

--- DataFrame Cargado Original ('match_stats') ---
Filas totales: 283834

,fixture_id,home_shots_total,away_shots_total,home_shots_on_goal,away_shots_on_goal,home_shots_inside_box,away_shots_inside_box,home_shots_outside_box,away_shots_outside_box,home_blocked_shots,...,home_goals_ht,away_goals_ht,home_xg_ht,away_xg_ht,stats_fetched_at,in_csv,in_pq,xg_covered,xg_nulled,known_at
0,287142,10.0,5.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-08-21 19:45:00
1,287156,10.0,12.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,NaN,NaN,NaT,True,True,False,True,2017-09-11 19:15:00
2,287157,8.0,8.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaT,True,True,False,True,2017-09-15 16:45:00
3,287173,6.0,9.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-09-24 16:15:00
4,287175,13.0,8.0,7.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-09-24 19:15:00

In [15]:
# Transformación mínima: Filtrar filas eliminando nulos de la primera columna real
primera_columna = df_original.columns[0]

# Crear el DataFrame transformado mediante un filtrado
df_transformado = df_original.dropna(subset=[primera_columna]).copy()

print(f"--- DataFrame Transformado (Sin nulos en '{primera_columna}') ---")
print(f"Filas resultantes: {len(df_transformado)}")
display(df_transformado.head())

--- DataFrame Transformado (Sin nulos en 'fixture_id') ---
Filas resultantes: 283834

,fixture_id,home_shots_total,away_shots_total,home_shots_on_goal,away_shots_on_goal,home_shots_inside_box,away_shots_inside_box,home_shots_outside_box,away_shots_outside_box,home_blocked_shots,...,home_goals_ht,away_goals_ht,home_xg_ht,away_xg_ht,stats_fetched_at,in_csv,in_pq,xg_covered,xg_nulled,known_at
0,287142,10.0,5.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-08-21 19:45:00
1,287156,10.0,12.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,NaN,NaN,NaT,True,True,False,True,2017-09-11 19:15:00
2,287157,8.0,8.0,4.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,NaN,NaN,NaT,True,True,False,True,2017-09-15 16:45:00
3,287173,6.0,9.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-09-24 16:15:00
4,287175,13.0,8.0,7.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,NaN,NaN,NaT,True,True,False,True,2017-09-24 19:15:00

In [16]:
# Pasar el DataFrame transformado a la segunda clase
summarizer = DatasetSummarizer(
    df=df_transformado, dataset_name=f"Soccer Dataset - {TABLA_ELEGIDA}"
)

# Generar el archivo .txt
archivo_generado = summarizer.summarize_to_txt(
    filename=f"resumen_{TABLA_ELEGIDA}_transformado"
)

📄 Archivo .txt de resumen generado exitosamente en: resumen_match_stats_transformado.txt

Explicación de la Transformación:
1. Se seleccionó la columna principal del dataset ('{}').
2. Se aplicó un filtro de limpieza con `.dropna(subset=[...])` para eliminar las filas con valores nulos en esa columna.
3. El número de registros se redujo de {:,} a {:,} filas.
4. El resumen '.txt' resultante refleja exactamente las dimensiones y estadísticas del DataFrame limpio.